os: linux
dist: xenial
git:
  depth: 1
language: go
go: "1.13"
env:
  - GO111MODULE=on
jobs:
  include:
    - stage: "HackerRank"
      script: ./run.sh challenges/hackerrank
    - stage: "Project Euler"
      script: ./run.sh challenges/project-euler

